try {
  hello()
} catch(error) {
  console.log(error)
}

try {
  goodBye()
} catch {
  console.log('Esta funci√≥n no existe')
}